# Generated by Django 2.1.2 on 2018-10-24 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Work',
            new_name='Projects',
        ),
    ]
