# Generated by Django 2.1.2 on 2018-10-25 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20181024_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
